name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends binfmt-support qemu-user-static
      - run: ./build.sh
      - run: ./test.sh shellsu-amd64
      - run: ./test.sh shellsu-i386
      - run: ./test.sh --debian shellsu-amd64
      - run: ./test.sh --debian shellsu-i386
      - run: docker build --pull --file hub/Dockerfile.alpine hub
      - run: docker build --pull --file hub/Dockerfile.debian hub
